name: mrs_ai
description: "A premium circular AI Assistant app named MRS AI, inspired by Jarvis."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  google_fonts: ^6.1.0
  speech_to_text: ^6.6.2
  flutter_tts: ^4.0.2
  http: ^1.2.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  torch_light: ^3.0.0
  flutter_volume_controller: ^3.0.2
  flutter_background_service: ^5.0.5
  screen_brightness: ^2.0.0
  battery_plus: ^6.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_volume_controller: any

flutter:
  uses-material-design: true
